

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  version: 1.17.0
  # apiVersions:
  # - monitoring.coreos.com/v1
  values:
  - values.yaml